# Message for logging from the Tap Game controller for analysis
Header header

int16 round_index
string current_round_action
string current_round_word

bool player_won_round_tap
string audio_file
string[] letters
float32[] scores
string[] passed
bool player_passed_round

int16 player_score
int16 robot_score

string[] word_curriculum
float32[] word_means
float32[] word_variances

string[] phoneme_curriculum
float32[] phoneme_means
float32[] phoneme_variances
