"""
This module serves as the official reference for the word list used in the Tap Game
"""

class Curriculum: # pylint: disable=too-few-public-methods
    """
    This class contains all static final members that correspond to the words we will teach
    """

    #BABY = 'BABY'
    #BATHTUB = 'BATHTUB'
    #BED = "BED"
    #BICYCLE = 'BICYCLE'
    BIRD = 'BIRD'
    BOAT = 'BOAT'
    BOWL = 'BOWL'
    BROOM = 'BROOM'
    BUCKET = 'BUCKET'    
    #BUS = 'BUS'
    CAR = 'CAR'
    #CASTLE = 'CASTLE'
    CAT = 'CAT'
    CHAIR = 'CHAIR'
    CLOCK = 'CLOCK'
    CLOUD = 'CLOUD'
    #COCONUT = 'COCONUT'
    COMPUTER = 'COMPUTER'
    #COUCH = 'COUCH'
    #CRIB = 'CRIB'
    #CUP = 'CUP'
    #DAD = 'DAD'
    DEER = 'DEER'
    DIG = 'DIG'
    DOG = 'DOG'
    DOLPHIN = 'DOLPHIN'
    #DOOR = 'DOOR'
    #DRESS = 'DRESS'
    #DRESSER = 'DRESSER'
    #DUCK = 'DUCK'
    #EAT = 'EAT'
    FATHER = "FATHER"
    #FISH = 'FISH'
    #FISHING = 'FISHING'
    FLOWER = 'FLOWER'    
    #FORK = 'FORK'
    FRIDGE = 'FRIDGE'
    #FROG = 'FROG'
    #GIRAFFE = 'GIRAFFE'
    GOAT = 'GOAT'
    HAT = 'HAT'
    HORSE = 'HORSE'
    IRON = 'IRON'
    #JUMPING = 'JUMPING'
    KETTLE = 'KETTLE'
    LAMP = 'LAMP'
    LION = 'LION'
    MAILBOX = 'MAILBOX'
    MIRROR = 'MIRROR'
    MONKEY = 'MONKEY'
    MOP = 'MOP'
    MOTHER = "MOTHER"
    #MOUNTAIN = 'MOUNTAIN'
    MOUSE = 'MOUSE'
    #PAINTING = 'PAINTING'
    PIG = 'PIG'
    PILLOW = 'PILLOW'
    #PLANE = 'PLANE'
    #RABBIT = 'RABBIT'
    ROOSTER = 'ROOSTER'
    #RUNNING = 'RUNNING'
    SEAL = 'SEAL'
    #SEASHELL = 'SEASHELL'
    SHEEP = 'SHEEP'
    SHIRT = 'SHIRT'
    #SHOES = 'SHOES'
    #SOCKS = 'SOCKS'
    SPOON = 'SPOON'
    STOVE = 'STOVE'
    SUN = 'SUN'
    #TABLE = 'TABLE'
    #TELEVISION = 'TELEVISION'
    #TOILET = 'TOILET'
    #TOWEL = 'TOWEL'
    TRACTOR = 'TRACTOR'
    TRAIN = 'TRAIN'
    #TREES = 'TREES'
    UMBRELLA = 'UMBRELLA'
    WINDOW = 'WINDOW'

    def __init__(self):
        return
